### ISSUE TITLE
Handle image error - display brand logo as a default fallback

### ISSUE THREAD

**Issue by 808vita** [Swetrix/marketplace-fe#68]
![image](https://github.com/Swetrix/marketplace-fe/assets/97225946/6e072857-8d26-496b-a1af-ad69a297b472)
Issue: image load error 
where this was encountered : https://marketplace.swetrix.com/

codebase:
https://github.com/Swetrix/marketplace-fe/blob/main/src/components/ExtensionsCard/index.jsx#L29
![image](https://github.com/Swetrix/marketplace-fe/assets/97225946/7a70075a-6426-4d1d-b0f3-6e2aa65925bd)

Nullish check is done for "mainImage" and placeholder url is set as fallback (if "mainImage" is nullish). But this does not handle image load error cases.

Suggestion:
Handle image errors throughout the site and display brand logo as a default fallback (or any other desired image).
Make use of onerror event and set the fallback image url .
https://www.w3schools.com/jsref/event_onerror.asp

**Comment by Blaumaus** [comment]
Hey, thanks for reporting it. The issue has been fixed
